/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class HomeVacaciones extends javax.swing.JFrame {

    /**
     * Creates new form HomeVacaciones
     */
    public HomeVacaciones() {
        initComponents();
        btnpdf.setBackground(new Color(248,217,217));
        btnexcel.setBackground(new Color(248,217,217));
        this.getContentPane().setBackground(new Color(229,230,242));
        txtdescripcion.setLineWrap(true);
        txtdescripcion.setWrapStyleWord(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        btncuenta = new javax.swing.JLabel();
        btnregresar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        btnexcel = new javax.swing.JButton();
        username1 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        titledescripcion = new javax.swing.JLabel();
        username4 = new javax.swing.JLabel();
        txtdiaspendientes = new javax.swing.JTextField();
        txtdiastomados1 = new javax.swing.JTextField();
        txtdiasdisponibles = new javax.swing.JTextField();
        username5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        btnpdf = new javax.swing.JButton();
        txtaño = new javax.swing.JComboBox<>();
        txtservidor1 = new javax.swing.JComboBox<>();
        txtindicacion = new javax.swing.JLabel();
        txtperiodo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/azuay_header9.png"))); // NOI18N

        btncuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cuenta (3).png"))); // NOI18N

        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(252, 248, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4)));

        username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username.setText("INFORMACION DE DIAS DISPONIBLES");

        pass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pass.setText("Período:");

        btnexcel.setBackground(new java.awt.Color(248, 217, 217));
        btnexcel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnexcel.setText("Generar Excel");

        username1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username1.setText("Servidor: ");

        username2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username2.setText("Dias pendientes");

        titledescripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titledescripcion.setText("Descripción");

        username4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username4.setText("Dias disponibles");

        txtdiaspendientes.setEditable(false);
        txtdiaspendientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtdiastomados1.setEditable(false);
        txtdiastomados1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtdiasdisponibles.setEditable(false);
        txtdiasdisponibles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        username5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username5.setText("Dias tomados");

        txtdescripcion.setColumns(20);
        txtdescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdescripcion.setRows(5);
        jScrollPane3.setViewportView(txtdescripcion);

        btnpdf.setBackground(new java.awt.Color(248, 217, 217));
        btnpdf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnpdf.setText("Generar PDF");

        txtaño.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtservidor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtservidor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtindicacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtindicacion.setText("Consigue el registro total:");

        txtperiodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtperiodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username5)
                            .addComponent(txtdiastomados1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(txtdiasdisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(username4)
                                .addGap(147, 147, 147)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdiaspendientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtindicacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnpdf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(btnexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(titledescripcion)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(username)
                        .addGap(204, 204, 204))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(username1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtservidor1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(pass)
                        .addGap(18, 18, 18)
                        .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass)
                    .addComponent(txtservidor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username1))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdiaspendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiasdisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiastomados1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(titledescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpdf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtindicacion))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Logo)
                        .addGap(421, 421, 421)
                        .addComponent(btncuenta))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btncuenta)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnregresar)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JLabel getLogo() {
        return Logo;
    }

    public void setLogo(JLabel Logo) {
        this.Logo = Logo;
    }

    public JLabel getBtncuenta() {
        return btncuenta;
    }

    public void setBtncuenta(JLabel btncuenta) {
        this.btncuenta = btncuenta;
    }

    public JButton getBtnexcel() {
        return btnexcel;
    }

    public void setBtnexcel(JButton btnexcel) {
        this.btnexcel = btnexcel;
    }

    public JButton getBtnpdf() {
        return btnpdf;
    }

    public void setBtnpdf(JButton btnpdf) {
        this.btnpdf = btnpdf;
    }

    public JLabel getBtnregresar() {
        return btnregresar;
    }

    public void setBtnregresar(JLabel btnregresar) {
        this.btnregresar = btnregresar;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JLabel getPass() {
        return pass;
    }

    public void setPass(JLabel pass) {
        this.pass = pass;
    }

    public JLabel getTitledescripcion() {
        return titledescripcion;
    }

    public void setTitledescripcion(JLabel titledescripcion) {
        this.titledescripcion = titledescripcion;
    }

    public JComboBox<String> getTxtaño() {
        return txtaño;
    }

    public void setTxtaño(JComboBox<String> txtaño) {
        this.txtaño = txtaño;
    }

    public JTextArea getTxtdescripcion() {
        return txtdescripcion;
    }

    public void setTxtdescripcion(JTextArea txtdescripcion) {
        this.txtdescripcion = txtdescripcion;
    }

    public JTextField getTxtdiasdisponibles() {
        return txtdiasdisponibles;
    }

    public void setTxtdiasdisponibles(JTextField txtdiasdisponibles) {
        this.txtdiasdisponibles = txtdiasdisponibles;
    }

    public JTextField getTxtdiaspendientes() {
        return txtdiaspendientes;
    }

    public void setTxtdiaspendientes(JTextField txtdiaspendientes) {
        this.txtdiaspendientes = txtdiaspendientes;
    }

    public JTextField getTxtdiastomados1() {
        return txtdiastomados1;
    }

    public void setTxtdiastomados1(JTextField txtdiastomados1) {
        this.txtdiastomados1 = txtdiastomados1;
    }

    public JLabel getTxtindicacion() {
        return txtindicacion;
    }

    public void setTxtindicacion(JLabel txtindicacion) {
        this.txtindicacion = txtindicacion;
    }

    public JComboBox<String> getTxtperiodo() {
        return txtperiodo;
    }

    public void setTxtperiodo(JComboBox<String> txtperiodo) {
        this.txtperiodo = txtperiodo;
    }

    public JComboBox<String> getTxtservidor1() {
        return txtservidor1;
    }

    public void setTxtservidor1(JComboBox<String> txtservidor1) {
        this.txtservidor1 = txtservidor1;
    }

    public JLabel getUsername() {
        return username;
    }

    public void setUsername(JLabel username) {
        this.username = username;
    }

    public JLabel getUsername1() {
        return username1;
    }

    public void setUsername1(JLabel username1) {
        this.username1 = username1;
    }

    public JLabel getUsername2() {
        return username2;
    }

    public void setUsername2(JLabel username2) {
        this.username2 = username2;
    }

    public JLabel getUsername4() {
        return username4;
    }

    public void setUsername4(JLabel username4) {
        this.username4 = username4;
    }

    public JLabel getUsername5() {
        return username5;
    }

    /**
     * @param args the command line arguments
     */
    public void setUsername5(JLabel username5) {
        this.username5 = username5;
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel btncuenta;
    private javax.swing.JButton btnexcel;
    private javax.swing.JButton btnpdf;
    private javax.swing.JLabel btnregresar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel titledescripcion;
    private javax.swing.JComboBox<String> txtaño;
    private javax.swing.JTextArea txtdescripcion;
    private javax.swing.JTextField txtdiasdisponibles;
    private javax.swing.JTextField txtdiaspendientes;
    private javax.swing.JTextField txtdiastomados1;
    private javax.swing.JLabel txtindicacion;
    private javax.swing.JComboBox<String> txtperiodo;
    private javax.swing.JComboBox<String> txtservidor1;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username4;
    private javax.swing.JLabel username5;
    // End of variables declaration//GEN-END:variables
}
