/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        btnvacaciones.setBackground(new Color(248,217,217));
        btnperiodo.setBackground(new Color(248,217,217));
        btninfo.setBackground(new Color(248,217,217));
        this.getContentPane().setBackground(new Color(229,230,242));
        btnvacaciones.setText(("<html><p>Consultar Vacaciones / </p><p align=\"center\">Generar archivo</p></html>"));
        btnperiodo.setText(("<html><p align=\"center\">Generar </p><p>Periodo Diario</p></html>"));
        btninfo.setText(("<html><p>Información del </p><p align = \"center\"> Personal</p></html>"));
        /*
        btnvacaciones.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        btnvacaciones.setVerticalAlignment((int) CENTER_ALIGNMENT);
    
        */}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btninfo = new javax.swing.JButton();
        btnvacaciones = new javax.swing.JButton();
        btnperiodo = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        btnback = new javax.swing.JLabel();
        btncuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(252, 248, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4)));

        btninfo.setBackground(new java.awt.Color(248, 217, 217));
        btninfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btninfo.setText("Vacaciones");

        btnvacaciones.setBackground(new java.awt.Color(248, 217, 217));
        btnvacaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnvacaciones.setText("Vacaciones");
        btnvacaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnperiodo.setBackground(new java.awt.Color(248, 217, 217));
        btnperiodo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnperiodo.setText("Vacaciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnvacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnvacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/azuay_header9.png"))); // NOI18N

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N

        btncuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cuenta (3).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logo)
                        .addGap(174, 174, 174)
                        .addComponent(btncuenta))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(66, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnback)
                            .addComponent(Logo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btncuenta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    /**
     * @param args the command line arguments
     */

    public JLabel getLogo() {
        return Logo;
    }

    public void setLogo(JLabel Logo) {
        this.Logo = Logo;
    }

    public JLabel getBtnback() {
        return btnback;
    }

    public void setBtnback(JLabel btnback) {
        this.btnback = btnback;
    }

    public JLabel getBtncuenta() {
        return btncuenta;
    }

    public void setBtncuenta(JLabel btncuenta) {
        this.btncuenta = btncuenta;
    }

    public JButton getBtninfo() {
        return btninfo;
    }

    public void setBtninfo(JButton btninfo) {
        this.btninfo = btninfo;
    }

    public JButton getBtnperiodo() {
        return btnperiodo;
    }

    public void setBtnperiodo(JButton btnperiodo) {
        this.btnperiodo = btnperiodo;
    }

    public JButton getBtnvacaciones() {
        return btnvacaciones;
    }

    public void setBtnvacaciones(JButton btnvacaciones) {
        this.btnvacaciones = btnvacaciones;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel btnback;
    private javax.swing.JLabel btncuenta;
    private javax.swing.JButton btninfo;
    private javax.swing.JButton btnperiodo;
    private javax.swing.JButton btnvacaciones;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
