/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 *
 * @author ASUS
 */
public class RegistroDiario extends javax.swing.JFrame {

    /**
     * Creates new form RegistroDiario
     */
    public RegistroDiario() {
        initComponents();
        
        initComponents();
        btnregistrar.setBackground(new Color(248,217,217));
        this.getContentPane().setBackground(new Color(229,230,242));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        Logo = new javax.swing.JLabel();
        btncuenta = new javax.swing.JLabel();
        btnregresar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JButton();
        username1 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        username5 = new javax.swing.JLabel();
        txtservidor = new javax.swing.JComboBox<>();
        txthorasextras = new javax.swing.JFormattedTextField();
        horasalida = new javax.swing.JFormattedTextField();
        horaingreso = new javax.swing.JFormattedTextField();
        txtfecha = new com.toedter.calendar.JDateChooser();
        username6 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        tiemporeceso = new javax.swing.JFormattedTextField();
        username7 = new javax.swing.JLabel();
        username8 = new javax.swing.JLabel();
        entradapermiso = new javax.swing.JFormattedTextField();
        salidapermiso = new javax.swing.JFormattedTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/azuay_header9.png"))); // NOI18N

        btncuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cuenta (3).png"))); // NOI18N

        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(252, 248, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4)));

        username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username.setText("REGISTRO DIARIO DEL PERSONAL");

        pass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pass.setText("Hora de Salida:");

        btnregistrar.setBackground(new java.awt.Color(248, 217, 217));
        btnregistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnregistrar.setText("Registrar el Dia");

        username1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username1.setText("Servidor: ");

        username2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username2.setText("Tiempo de Receso:");

        username5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username5.setText("Fecha:");

        txtservidor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtservidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        try {
            txthorasextras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txthorasextras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txthorasextras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            horasalida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        horasalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        horasalida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            horaingreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        horaingreso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        horaingreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtfecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        username6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username6.setText("Hora de Ingreso:");

        username3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username3.setText("Horas Extras:");

        try {
            tiemporeceso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tiemporeceso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tiemporeceso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        username7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username7.setText("Hora entrada de Permiso:");

        username8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username8.setText("Hora salida de Permiso:");

        try {
            entradapermiso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        entradapermiso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradapermiso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            salidapermiso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        salidapermiso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        salidapermiso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCheckBox1.setText("Permiso de Salida");

        jCheckBox2.setText("Horas Extras");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(username)
                .addGap(272, 272, 272))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(username5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(username1)
                                                .addComponent(username6))
                                            .addGap(5, 5, 5)))
                                    .addGap(53, 53, 53)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtservidor, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(horaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(137, 137, 137)
                                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCheckBox1)
                                                .addComponent(jCheckBox2)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(167, 167, 167)
                                            .addComponent(salidapermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(54, 54, 54)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(username2)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(25, 25, 25)
                                                    .addComponent(username3))
                                                .addComponent(pass, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addComponent(username7)))
                                    .addGap(41, 41, 41)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tiemporeceso, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(horasalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(entradapermiso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txthorasextras, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(username8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtservidor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username1))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(horasalida, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(horaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(username6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(username5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(username2)
                                .addComponent(txthorasextras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tiemporeceso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salidapermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradapermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncuenta))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btncuenta)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnregresar)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JLabel getLogo() {
        return Logo;
    }

    public void setLogo(JLabel Logo) {
        this.Logo = Logo;
    }

    public JLabel getBtncuenta() {
        return btncuenta;
    }

    public void setBtncuenta(JLabel btncuenta) {
        this.btncuenta = btncuenta;
    }

    public JButton getBtnregistrar() {
        return btnregistrar;
    }

    public void setBtnregistrar(JButton btnregistrar) {
        this.btnregistrar = btnregistrar;
    }

    public JLabel getBtnregresar() {
        return btnregresar;
    }

    public void setBtnregresar(JLabel btnregresar) {
        this.btnregresar = btnregresar;
    }

    public JFormattedTextField getEntradapermiso() {
        return entradapermiso;
    }

    public void setEntradapermiso(JFormattedTextField entradapermiso) {
        this.entradapermiso = entradapermiso;
    }

    public JFormattedTextField getHoraingreso() {
        return horaingreso;
    }

    public void setHoraingreso(JFormattedTextField horaingreso) {
        this.horaingreso = horaingreso;
    }

    public JFormattedTextField getHorasalida() {
        return horasalida;
    }

    public void setHorasalida(JFormattedTextField horasalida) {
        this.horasalida = horasalida;
    }

    public JCheckBox getjCheckBox1() {
        return jCheckBox1;
    }

    public void setjCheckBox1(JCheckBox jCheckBox1) {
        this.jCheckBox1 = jCheckBox1;
    }

    public JCheckBox getjCheckBox2() {
        return jCheckBox2;
    }

    public void setjCheckBox2(JCheckBox jCheckBox2) {
        this.jCheckBox2 = jCheckBox2;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JProgressBar getjProgressBar1() {
        return jProgressBar1;
    }

    public void setjProgressBar1(JProgressBar jProgressBar1) {
        this.jProgressBar1 = jProgressBar1;
    }

    public JLabel getPass() {
        return pass;
    }

    public void setPass(JLabel pass) {
        this.pass = pass;
    }

    public JFormattedTextField getSalidapermiso() {
        return salidapermiso;
    }

    public void setSalidapermiso(JFormattedTextField salidapermiso) {
        this.salidapermiso = salidapermiso;
    }

    public JFormattedTextField getTiemporeceso() {
        return tiemporeceso;
    }

    public void setTiemporeceso(JFormattedTextField tiemporeceso) {
        this.tiemporeceso = tiemporeceso;
    }

    public JDateChooser getTxtfecha() {
        return txtfecha;
    }

    public void setTxtfecha(JDateChooser txtfecha) {
        this.txtfecha = txtfecha;
    }

    public JFormattedTextField getTxthorasextras() {
        return txthorasextras;
    }

    public void setTxthorasextras(JFormattedTextField txthorasextras) {
        this.txthorasextras = txthorasextras;
    }

    public JComboBox<String> getTxtservidor() {
        return txtservidor;
    }

    public void setTxtservidor(JComboBox<String> txtservidor) {
        this.txtservidor = txtservidor;
    }

    public JLabel getUsername() {
        return username;
    }

    public void setUsername(JLabel username) {
        this.username = username;
    }

    public JLabel getUsername1() {
        return username1;
    }

    public void setUsername1(JLabel username1) {
        this.username1 = username1;
    }

    public JLabel getUsername2() {
        return username2;
    }

    public void setUsername2(JLabel username2) {
        this.username2 = username2;
    }

    public JLabel getUsername3() {
        return username3;
    }

    public void setUsername3(JLabel username3) {
        this.username3 = username3;
    }

    public JLabel getUsername5() {
        return username5;
    }

    public void setUsername5(JLabel username5) {
        this.username5 = username5;
    }

    public JLabel getUsername6() {
        return username6;
    }

    public void setUsername6(JLabel username6) {
        this.username6 = username6;
    }

    public JLabel getUsername7() {
        return username7;
    }

    public void setUsername7(JLabel username7) {
        this.username7 = username7;
    }

    public JLabel getUsername8() {
        return username8;
    }

    /**
     * @param args the command line arguments
     */
    public void setUsername8(JLabel username8) {
        this.username8 = username8;
    }

    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel btncuenta;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JLabel btnregresar;
    private javax.swing.JFormattedTextField entradapermiso;
    private javax.swing.JFormattedTextField horaingreso;
    private javax.swing.JFormattedTextField horasalida;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel pass;
    private javax.swing.JFormattedTextField salidapermiso;
    private javax.swing.JFormattedTextField tiemporeceso;
    private com.toedter.calendar.JDateChooser txtfecha;
    private javax.swing.JFormattedTextField txthorasextras;
    private javax.swing.JComboBox<String> txtservidor;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username5;
    private javax.swing.JLabel username6;
    private javax.swing.JLabel username7;
    private javax.swing.JLabel username8;
    // End of variables declaration//GEN-END:variables
}
