/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        btnregistrar.setBackground(new Color(248,217,217));
        this.getContentPane().setBackground(new Color(229,230,242));
        txtcargo.setLineWrap(true);
        txtcargo.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        titlecedula = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JButton();
        titleapellido = new javax.swing.JLabel();
        titleusername = new javax.swing.JLabel();
        titlenombre = new javax.swing.JLabel();
        titlepass = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        titlecargo = new javax.swing.JLabel();
        comboocupacion = new javax.swing.JComboBox<>();
        titleocupacion = new javax.swing.JLabel();
        titlecorreo = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txttlfn = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        titleocupacion1 = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcargo = new javax.swing.JTextArea();
        username = new javax.swing.JLabel();
        titleocupacion2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        btnregresar = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/azuay_header9.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(252, 248, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4), new java.awt.Color(255, 4, 4)));

        titlecedula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titlecedula.setText("Cédula");

        btnregistrar.setBackground(new java.awt.Color(248, 217, 217));
        btnregistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnregistrar.setText("Registrar");

        titleapellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleapellido.setText("Apellido");

        titleusername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleusername.setText("Nombre de Usuario");

        titlenombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titlenombre.setText("Nombres");

        titlepass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titlepass.setText("Contraseña");

        txtpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        titlecargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titlecargo.setText("Cargo");

        comboocupacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboocupacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal TTHH", "Funcionario" }));

        titleocupacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleocupacion.setText("Ocupación");

        titlecorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titlecorreo.setText("Correo");

        txtcedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txttlfn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtapellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtcorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtnombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        titleocupacion1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleocupacion1.setText("Trabajador");

        combotipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código de Trabajo", "LOSEP" }));

        txtcargo.setColumns(20);
        txtcargo.setRows(5);
        jScrollPane1.setViewportView(txtcargo);

        username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username.setText("REGISTRO DE EMPLEADO");

        titleocupacion2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleocupacion2.setText("Telefono");

        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combotipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(comboocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(titlepass)
                            .addGap(62, 62, 62)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(titleocupacion2)
                                .addComponent(titleusername))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txttlfn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtusername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleocupacion1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(titleocupacion)
                                    .addComponent(titlecedula, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(username)
                .addGap(275, 275, 275))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titlenombre)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(titlecargo)
                                .addComponent(titlecorreo)))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlenombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlecedula))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleocupacion)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleapellido))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleocupacion1)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlecorreo))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleocupacion2)
                            .addComponent(txttlfn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titlecargo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleusername)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlepass))
                .addGap(26, 26, 26)
                .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnregresar)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JLabel getLogo() {
        return Logo;
    }

    public void setLogo(JLabel Logo) {
        this.Logo = Logo;
    }

    public JButton getBtnregistrar() {
        return btnregistrar;
    }

    public void setBtnregistrar(JButton btnregistrar) {
        this.btnregistrar = btnregistrar;
    }

    public JLabel getBtnregresar() {
        return btnregresar;
    }

    public void setBtnregresar(JLabel btnregresar) {
        this.btnregresar = btnregresar;
    }

    public JComboBox<String> getComboocupacion() {
        return comboocupacion;
    }

    public void setComboocupacion(JComboBox<String> comboocupacion) {
        this.comboocupacion = comboocupacion;
    }

    public JComboBox<String> getCombotipo() {
        return combotipo;
    }

    public void setCombotipo(JComboBox<String> combotipo) {
        this.combotipo = combotipo;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JLabel getTitleapellido() {
        return titleapellido;
    }

    public void setTitleapellido(JLabel titleapellido) {
        this.titleapellido = titleapellido;
    }

    public JLabel getTitlecargo() {
        return titlecargo;
    }

    public void setTitlecargo(JLabel titlecargo) {
        this.titlecargo = titlecargo;
    }

    public JLabel getTitlecedula() {
        return titlecedula;
    }

    public void setTitlecedula(JLabel titlecedula) {
        this.titlecedula = titlecedula;
    }

    public JLabel getTitlecorreo() {
        return titlecorreo;
    }

    public void setTitlecorreo(JLabel titlecorreo) {
        this.titlecorreo = titlecorreo;
    }

    public JLabel getTitlenombre() {
        return titlenombre;
    }

    public void setTitlenombre(JLabel titlenombre) {
        this.titlenombre = titlenombre;
    }

    public JLabel getTitleocupacion() {
        return titleocupacion;
    }

    public void setTitleocupacion(JLabel titleocupacion) {
        this.titleocupacion = titleocupacion;
    }

    public JLabel getTitleocupacion1() {
        return titleocupacion1;
    }

    public void setTitleocupacion1(JLabel titleocupacion1) {
        this.titleocupacion1 = titleocupacion1;
    }

    public JLabel getTitleocupacion2() {
        return titleocupacion2;
    }

    public void setTitleocupacion2(JLabel titleocupacion2) {
        this.titleocupacion2 = titleocupacion2;
    }

    public JLabel getTitlepass() {
        return titlepass;
    }

    public void setTitlepass(JLabel titlepass) {
        this.titlepass = titlepass;
    }

    public JLabel getTitleusername() {
        return titleusername;
    }

    public void setTitleusername(JLabel titleusername) {
        this.titleusername = titleusername;
    }

    public JTextField getTxtapellido() {
        return txtapellido;
    }

    public void setTxtapellido(JTextField txtapellido) {
        this.txtapellido = txtapellido;
    }

    public JTextArea getTxtcargo() {
        return txtcargo;
    }

    public void setTxtcargo(JTextArea txtcargo) {
        this.txtcargo = txtcargo;
    }

    public JTextField getTxtcedula() {
        return txtcedula;
    }

    public void setTxtcedula(JTextField txtcedula) {
        this.txtcedula = txtcedula;
    }

    public JTextField getTxtcorreo() {
        return txtcorreo;
    }

    public void setTxtcorreo(JTextField txtcorreo) {
        this.txtcorreo = txtcorreo;
    }

    public JTextField getTxtnombre() {
        return txtnombre;
    }

    public void setTxtnombre(JTextField txtnombre) {
        this.txtnombre = txtnombre;
    }

    public JPasswordField getTxtpass() {
        return txtpass;
    }

    public void setTxtpass(JPasswordField txtpass) {
        this.txtpass = txtpass;
    }

    public JTextField getTxttlfn() {
        return txttlfn;
    }

    public void setTxttlfn(JTextField txttlfn) {
        this.txttlfn = txttlfn;
    }

    public JTextField getTxtusername() {
        return txtusername;
    }

    public void setTxtusername(JTextField txtusername) {
        this.txtusername = txtusername;
    }

    public JLabel getUsername() {
        return username;
    }

    /**
     * @param args the command line arguments
     */
    public void setUsername(JLabel username) {
        this.username = username;
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JLabel btnregresar;
    private javax.swing.JComboBox<String> comboocupacion;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel titleapellido;
    private javax.swing.JLabel titlecargo;
    private javax.swing.JLabel titlecedula;
    private javax.swing.JLabel titlecorreo;
    private javax.swing.JLabel titlenombre;
    private javax.swing.JLabel titleocupacion;
    private javax.swing.JLabel titleocupacion1;
    private javax.swing.JLabel titleocupacion2;
    private javax.swing.JLabel titlepass;
    private javax.swing.JLabel titleusername;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextArea txtcargo;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txttlfn;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
